services:
  server:
    build:
      context: ./api
    ports:
      - 3000:3000
    restart: always

  static:
    build:
      context: ./static
    ports:
      - 8080:8080
    depends_on:
      - server
    restart: always
